# ~/.streamlit/config.toml
[server]
# Setting the port for the Streamlit server
port = 8501
# Limiting the maximum upload size (in megabytes)
maxUploadSize = 1024
# Setting the maximum allowable size for in-memory cache (in megabytes)
maxCachedFileSize = 1024

[client]
# Controlling the maximum message size that the frontend can receive (in bytes)
maxMessageSize = 10485760

[theme]
# Enabling dark mode theme
base = "dark"
primaryColor = "#1E88E5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"

